[package]
name = "andremhpra/camray"
version = "0.1.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "Wrapper for raycasting from the player's camera to the player's mouse, supports tap position for mobile support."

[dependencies]
