[package]
name = "andremhpra/validate-type"
version = "0.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
description = "Holds a list of functions to validate common types, intended for server-side remote events."

[dependencies]