[package]
name = "andremhpra/orderedprofile"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
description = "OOP implementation of OrderedDataStore."

[dependencies]