[package]
name = "andremhpra/deepcopy"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "Deep copies the provided table with strict-typing support."

[dependencies]